import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
execFileSync(process.execPath, ['--check', 'src/studio/public/app.js']);
execFileSync(process.execPath, ['--check', 'src/studio/public/workbench.js']);
execFileSync(process.execPath, ['--check', 'src/studio/public/integrations.js']);
execFileSync(process.execPath, ['--check', 'src/studio/public/chat-output.js']);
execFileSync(process.execPath, ['--check', 'src/studio/public/team-map.js']);
fs.mkdirSync('dist/studio/public', { recursive: true });
for (const name of fs.readdirSync('src/studio/public')) fs.copyFileSync(`src/studio/public/${name}`, `dist/studio/public/${name}`);
fs.cpSync('src/skills', 'dist/skills', { recursive: true });
fs.cpSync('src/vendor-skills', 'dist/vendor-skills', { recursive: true });
fs.cpSync('src/template-assets', 'dist/template-assets', { recursive: true });
