import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {safePath,isSensitivePath,redact} from './security.js';
export function inspectProject(root:string){
 const observations:{file:string;line?:number;code:string;message:string;severity:'info'|'warning'}[]=[],files:{path:string;sha256:string}[]=[],dependencies:{name:string;version:string;scope:string}[]=[];
 const read=(relative:string)=>{try{if(isSensitivePath(relative))return;const file=safePath(root,relative);const stat=fs.statSync(file);if(!stat.isFile()||stat.size>512*1024)return;const text=fs.readFileSync(file,'utf8');files.push({path:relative,sha256:crypto.createHash('sha256').update(text).digest('hex')});return text;}catch{return;}};
 const manifest=read('package.json');let pkg:any;try{pkg=manifest?JSON.parse(manifest):undefined;}catch{observations.push({file:'package.json',code:'invalid_manifest',message:'Manifest JSON cannot be parsed.',severity:'warning'});}
 for(const scope of ['dependencies','devDependencies','optionalDependencies'])for(const [name,version] of Object.entries(pkg?.[scope]||{}).slice(0,300)){if(typeof version!=='string')continue;dependencies.push({name,version:redact(version).replace(/(https?:\/\/)[^/\s@]+@/gi,'$1[REDACTED]@'),scope});if(/^(?:https?:|git\+|github:|file:|link:)/i.test(version))observations.push({file:'package.json',code:'dependency_source',message:`${name}: non-registry or local dependency; inspect trust and pinning.`,severity:'warning'});}
 for(const name of ['preinstall','install','postinstall','prepare'])if(typeof pkg?.scripts?.[name]==='string')observations.push({file:'package.json',code:'lifecycle_script',message:`${name}: install-time code exists; inspect it before installing.`,severity:'warning'});
 const lock=read('package-lock.json');let resolvedCount=0;try{const data=lock?JSON.parse(lock):null;for(const [name,value] of Object.entries(data?.packages||{}).slice(0,5000)){const item=value as any;if(!name||item.link)continue;resolvedCount++;if(typeof item.resolved==='string'&&/^https?:/.test(item.resolved)&&!item.integrity)observations.push({file:'package-lock.json',code:'missing_integrity',message:`${name}: downloaded entry has no integrity hash.`,severity:'warning'});}}catch{observations.push({file:'package-lock.json',code:'invalid_lockfile',message:'Lockfile JSON cannot be parsed.',severity:'warning'});}
 const sourceFiles:string[]=[];let truncated=false;const walk=(relative:string,depth:number)=>{if(depth>4){truncated=true;return;}let entries:fs.Dirent[];try{entries=fs.readdirSync(safePath(root,relative||'.'),{withFileTypes:true});}catch{return;}for(const entry of entries){if(sourceFiles.length>=120){truncated=true;break;}if(entry.isSymbolicLink()||['node_modules','.git','.vibe','dist','build','release','test-results','reports'].includes(entry.name))continue;const next=path.join(relative,entry.name);if(isSensitivePath(next))continue;if(entry.isDirectory())walk(next,depth+1);else if(/\.(?:[cm]?[jt]s|tsx|jsx)$/.test(entry.name))sourceFiles.push(next);}};walk('',0);
 if(dependencies.some(d=>d.name==='electron'))for(const file of sourceFiles){const text=read(file);if(!text)continue;text.split(/\r?\n/).forEach((line,index)=>{for(const [code,pattern,message] of [['electron_node_integration',/\bnodeIntegration\s*:\s*true\b/,'Renderer Node integration literal found.'],['electron_context_isolation',/\bcontextIsolation\s*:\s*false\b/,'Disabled context isolation literal found.'],['electron_web_security',/\bwebSecurity\s*:\s*false\b/,'Disabled web security literal found.']] as const)if(pattern.test(line))observations.push({file,line:index+1,code,message:message+' Static candidate: inspect executable configuration; comments/examples can match.',severity:'warning'});});}
 return {version:1,kind:'local-project-inspection',recordedAt:new Date().toISOString(),runtime:pkg?'node':'unknown',electron:dependencies.some(d=>d.name==='electron'),files,dependencies,lockfile:{present:!!lock,resolvedPackages:resolvedCount},observations:observations.slice(0,300),truncated:truncated||observations.length>300,limits:{maxFileBytes:512*1024,maxSourceFiles:120,maxDepth:4},verdict:'UNVERIFIED',caveats:['Static local observations are candidates, not confirmed vulnerabilities or CVE coverage.','No dependencies installed, scripts executed or external targets contacted.','Files outside scan limits and dynamic runtime configuration require independent inspection.']};
}
